var fs = require('fs')
var trumpet = require('trumpet')
var tr = trumpet()
tr.pipe(process.stdout)
var index = fs.readFileSync('./index.html')
tr.select('body', function (elem) {
  var body = elem.createStream()
  body.push(index)
  body.pipe(body)
})
fs.createReadStream('./frame.html').pipe(tr)
